### ISSUE TITLE
Feature Request: Conjugated forms of words auto-redirect to original word

### ISSUE THREAD

**Issue by yephny** [tirkarthi/NotificationDictionary#22]
When you look up the definition of "notified", you get "past participle of notify". Then you have to manually look up "notify". It should instead redirect to "notify" automatically. 

I don't know how easy this is to implement but I don't see the point of not showing the definition of a word. Yes, the user might know the original word while being unaware of its conjugation in different tenses, in which case this would help. However, they would still get that the word they're looking up is a conjugated form of the original word that the app has redirected them to, while making sure they know what the word means by showing its definition.

**Comment by Noitarud** [comment]
Maybe follow with the base after a semicolon.
"plural of"(-s), "property or trait"(snobbery), …

**Comment by tirkarthi** [comment]
I have tried a simple regex match to resolve the word for plural, singular, past participle etc. This works for now as below to include inline meaning inside braces. One improvement is that the redirected word might have multiple meanings where outdated meanings were shown in very few cases since the first result is used and there is no priority. Thanks @Noitarud for the suggestion.

Word : Apples
Current : Plural of Apple
With Patch : Plural of Apple (A common, round fruit)

https://github.com/tirkarthi/NotificationDictionary/pull/31

**Comment by heyheyhello** [comment]
That sounds like a perfectly fine work around, thank you for implementing it!
