### ISSUE TITLE
Access from "Share Via" menu

### ISSUE THREAD

**Issue by VishnuSanal** [tirkarthi/NotificationDictionary#34]
Add NotificationDictionary to Android's "Share Via" menu; so that we can select a word, click on share & fetch the meaning.

PS: if you are interested in accepting this idea, I'd like to work on this :)

**Comment by VishnuSanal** [comment]
> Hi, thanks for the report. Just trying to understand is there any advantage to this than selecting the word and clicking on meaning in context menu as I see them having similar number of clicks and actions.

hmm, I was thinking of the cases when the "meaning" context item does not appear. for instance on the GMail application, on Twitter, from some kind of text box (say on WhatsApp) etc.

(CMMIW: whether it is a bug that the context item doesn't appear? is it specific to my device? 🤔)

**Comment by tirkarthi** [comment]
See also https://github.com/tirkarthi/NotificationDictionary/issues/28 and https://github.com/tirkarthi/NotificationDictionary/issues/25 . It could be that some apps implement custom select interface where meaning might not show up as is case with whatsapp where the whole message is selected and a single word from message cannot be selected. Since dictionary acts on single word it might not be useful in those cases.

**Comment by VishnuSanal** [comment]
> See also #28 and #25 . It could be that some apps implement custom select interface where meaning might not show up

I see. this is exactly what I meant as a use case for this feature. please note 'share' item always appeared on screen grabs provided in the tagged issues.

> as is case with whatsapp where the whole message is selected and a single word from message cannot be selected. Since dictionary acts on single word it might not be useful in those cases.

I meant text fields in general; WhatsApp was used as an example! We can select single words from a text field & then click share from the context menu.

**Comment by tirkarthi** [comment]
I have added a PR for this https://github.com/tirkarthi/NotificationDictionary/pull/36 . It seems in Samsung version when the text is selected in browser like brave the URL along with selected text is also added. E.g. when test in a page is selected then `"test" https://example.com` is received as the intent text in the app that will result in no results.

**Comment by VishnuSanal** [comment]
> I have added a PR for this https://github.com/tirkarthi/NotificationDictionary/pull/36 . It seems in Samsung version when the text is selected in browser like brave the URL along with selected text is also added. E.g. when test in a page is selected then `"test" https://example.com` is received as the intent text in the app that will result in no results.

Let me check.

**Comment by in-plaintext** [comment]
[Termux](https://github.com/termux/termux-app) has its own or non-standard context menu — at the time there doesn't be any way to share words to Notification Dictionary, a great drawback since I mainly use the Linux environment on Android.

[Thankfully a PR has been created](https://github.com/tirkarthi/NotificationDictionary/pull/36).

**Comment by tirkarthi** [comment]
Merged as part of #36. Closing. Thanks @VishnuSanal for the idea.
