### ISSUE TITLE
"Meaning" button doesn't do anything

### ISSUE THREAD

**Issue by cat20958** [tirkarthi/NotificationDictionary#38]
After clicking on the button, nothing happens and i dont get a notification. I checked the app  settings, and the "allow notifications" permission was turned off. The issue
is that it's also greyed out, so i cant turn it on to fix the problem
![IMG_20231001_112416](https://github.com/tirkarthi/NotificationDictionary/assets/146623141/a6b45d39-197a-4f24-aab3-a4f89201777a)

**Comment by tirkarthi** [comment]
Hi, Thanks for the report. This has been fixed in below commit to add notifications permission for Android 13+ and to prompt for access during startup. I have pushed version v0.0.20 for google play review and will close this once the version is deployed.

https://github.com/tirkarthi/NotificationDictionary/commit/14833f4e664986f562582a544db5affacac3a8be

**Comment by tirkarthi** [comment]
@cat20958 The updated version v0.0.20 is not available in play store. Can you please try the update now? Thanks,

**Comment by cat20958** [comment]
Works as intended now. Thank you.
