### ISSUE TITLE
Is the development is dead for the app

### ISSUE THREAD

**Issue by saltsoftdrink** [tirkarthi/NotificationDictionary#60]

**Comment by tirkarthi** [comment]
@saltsoftdrink The app is developed in my free time. My free time for open source is limited due to day job and personal reasons. The app is stable. I have created issues for most requested features like history of words, meanings and other translations. I will try to make releases with new features as my time permits.

**Comment by tirkarthi** [comment]
Thanks @saltsoftdrink . I am glad you found the app helpful.
